### ISSUE TITLE
✨ Feat: Support current Debian stable version (Trixie 13)

### ISSUE THREAD

**Issue by piRGoif** [tracim/tracim#6859]
### Current status

Currently,

- Tracim only supports Python 3.9 to 3.11
- Docker image rely on Debian 11

Also, python 3.12+ is not supported:

- Python 3.12 support see #6711
- Python 3.13 support see #6856

Also we detected issues with the setup when running on Debian 13 with Python 3.0 or 3.11: see #6766

### Feature description

It is expected to upgrade the building blocks on which Tracim relies:

- Use Debian Trixie (13) as the docker root image
- Support Python 3.13 (Python 3.12 is not in the target)
- Use Pushpin from the project .deb repository: https://pushpin.org/docs/install/

There are multiple related issues:

- FIX 
  - Python version support
    - #6856
  - issues when running on Debian 13
    - #6766
    - #6864
    - #6865
- To do next
  - #6866
- WONTFIX 
  - #6711: goal is to support Python 3.13 and not lower versions
  - #6863: discovered during work on Python 3.13, but this is unrelated and out of scope

### How it works

- No issue when running setup
- No issue when operating the software

**Comment by lebouquetin** [comment]
For marshmallow upgrade to 3.X, see the work done in hapic: https://github.com/algoo/hapic/pull/219/changes 

Typical refactor:

```
        dump_data = self.schema.dump(clean_data).data

        # Validate
        errors = self.schema.load(dump_data).errors
        if errors:
            raise OutputValidationException("Error when validate input: {}".format(str(errors)))

        return dump_data
```

replaced with

```
        try:
            self.schema.load(clean_data)
        except MarshmallowValidationError as error:
            raise OutputValidationException("Error when validate input: {}".format(str(error.messages)))
        else:
            return self.schema.dump(clean_data)
```

@piRGoif

**Comment by piRGoif** [comment]
I've updated the description to have a clear map of all the related tickets

**Comment by piRGoif** [comment]
Consolidated documentation about changes made inside PR #6860

## Tracim code
### SyntaxWarning about \d in regexp pattern
Became a SyntaxWarning (shown by default, cannot be filtered) in Python 3.12 instead of a DeprecationWarning (hidden by default)    
See https://docs.python.org/3/whatsnew/3.12.html#other-language-changes

> A backslash-character pair that is not a valid escape sequence now generates a SyntaxWarning, instead of DeprecationWarning.

Solution is to use string r prefix, see https://docs.python.org/3.12/library/re.html

Also removed the "# noqa: W605" comment, it was a flake8 ignore directive


## Python dependencies
### requirements-build.txt
pkgutil.ImpImporter removed in Python 3.13
Updated faulty libs to the first version without error under Python 3.13: pip, setuptools
### requirements-db-postgres.txt
psycopg2 : it fails when building the image.  
We are asking for 2.9.9, but we can see in the changelog Python 3.13 compatibility was added in 3.9.10 : https://www.psycopg.org/docs/news.html#what-s-new-in-psycopg-2-9-10

### requirements-devtool.txt
There are warnings in server log "Readline features including tab completion have been disabled because no supported version of readline was found"
To solve that I initially added gnureadline 8.2.13 ("Supports Python 3.13 (including free-threaded version)" in https://github.com/ludwigschwardt/python-gnureadline/tags)
But adding a dependency to only remove one warning is too much so we finally didn't add it.

| Library      | Pinned version | First Python 3.13 compatible version                                                                                                                                                                                                                                                                                                       | Source                                                                          |
| ------------ | -------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------- |
| flake8       | 6.0.0          | Not explicitly mentioned in any release note (7.3.0 added 3.14, 3.13 was never called out) => update to latest 6.* (BC in 7.0.0)                                                                                                                                                                                                           | [release notes](https://flake8.pycqa.org/en/latest/release-notes/index.html)    |
| isort        | v5.10.1        | **6.0.0** (2024-01-27) — "Python 3.13 support" => seems like there aren't no impacting BC                                                                                                                                                                                                                                                  | [releases](https://github.com/PyCQA/isort/releases)                             |
| mypy         | 1.9.0          | **1.12** (2024-10-14) — "Basic Support for Python 3.13 — This release adds partial support for Python 3.13 features and compiled binaries for Python 3.13." => changelog adds 3.13 mention up to 1.18 so updating to that version                                                                                                          | [CHANGELOG.md](https://github.com/python/mypy/blob/master/CHANGELOG.md)         |
| pre-commit   | 2.18.1         | Not explicitly mentioned in changelog                                                                                                                                                                                                                                                                                                      | [CHANGELOG.md](https://github.com/pre-commit/pre-commit/blob/main/CHANGELOG.md) |
| black        | 23.3.0         | **24.10.0** (Oct 2024) — "officially tested with Python 3.13 and provides Python 3.13 mypyc-compiled wheels"                                                                                                                                                                                                                               | [CHANGES.md](https://github.com/psf/black/blob/main/CHANGES.md)                 |
| flake8-black | 0.3.6          | Not explicitly mentioned in GH releases (latest: v4.0.0 Sep 2025, was dormant Dec 2022 → Sep 2025), but present in the README Python 3.13 support from v0.3.7                                                                                                                                                                              | [README](https://github.com/peterjc/flake8-black#version-history)               |
| flake8-isort | 6.0.0          | **6.1.2** (2025-01-29) — "Drop python 3.8, and add python 3.13"                                                                                                                                                                                                                                                                            | [CHANGES.rst](https://github.com/gforcada/flake8-isort/blob/main/CHANGES.rst)   |
| pip-tools    | 7.4.1          | **7.5.2** (2025-11-11) — "Test and declare Python 3.13 support", but BC on pip compile in 7.5.0 : [https://github.com/jazzband/pip-tools/blob/main/CHANGELOG.md#removals-and-backward-incompatible-breaking-changes-1](https://github.com/jazzband/pip-tools/blob/main/CHANGELOG.md#removals-and-backward-incompatible-breaking-changes-1) | [CHANGELOG.md](https://github.com/jazzband/pip-tools/blob/main/CHANGELOG.md)    |
### requirements-full-preview-generator.txt
Pip generates a "no matching distribution error"
- vtk : [https://pypi.org/project/vtk/9.4.0/#files](https://pypi.org/project/vtk/9.4.0/#files) cp313 wheels
- rawpy : [https://github.com/letmaik/rawpy/releases/tag/v0.24.0](https://github.com/letmaik/rawpy/releases/tag/v0.24.0) "Add Python 3.13 wheels"
- numpy : [https://github.com/numpy/numpy/releases/tag/v2.1.0](https://github.com/numpy/numpy/releases/tag/v2.1.0) "Support for Python 3.13"
### requirements-storage-s3.txt
- boto3 and botocore : https://github.com/boto/boto3/blob/develop/CHANGELOG.rst => Needs Boto3 1.35.36
- s3transfer : https://github.com/boto/s3transfer/blob/develop/CHANGELOG.rst#0103 "Added provisional Python 3.13 support"
### requirements-test.txt
| Library | Pinned version | First Python 3.13 compatible version | Source |
|---|---|---|---|
| WebTest | 2.0.35 | Not mentioned in changelog | [changelog](https://docs.pylonsproject.org/projects/webtest/en/latest/changelog.html) |
| pytest | 7.2.2 | **8.2.1** (2024-05-19) — "Support for Python 3.13 (beta1 at the time of writing)" | [releases](https://github.com/pytest-dev/pytest/releases) |
| pytest-dotenv | 0.4.0 | Not mentioned — project archived Jul 2025 | [repo](https://github.com/quiqua/pytest-dotenv) |
| pytest-services | 2.0.1 | Not mentioned in changelog | [CHANGES.rst](https://github.com/pytest-dev/pytest-services/blob/main/CHANGES.rst) |
| pytest-testinfra | 6.8.0 | **10.2.0** (2025-03-29) — "Also run lint for py 3.12 and 3.13" | [CHANGELOG.rst](https://github.com/pytest-dev/pytest-testinfra/blob/main/CHANGELOG.rst) |
| pytest-timeout | 1.4.2 | **2.4.0** (2025-05-05) — "Add python 3.13" | [tags](https://github.com/pytest-dev/pytest-timeout/tags) |
| pytest-forked | 1.3.0 | Not mentioned — last explicit Python support: 3.11 (v1.5.0) | [CHANGELOG.rst](https://github.com/pytest-dev/pytest-forked/blob/master/CHANGELOG.rst) |
| responses | 0.10.11 | **0.25.7** (2024-03-11) — "Added support for python 3.13" | [releases](https://github.com/getsentry/responses/releases) |
| mock | 3.0.5 | Not mentioned in changelog | [CHANGELOG.rst](https://github.com/testing-cabal/mock/blob/master/CHANGELOG.rst) |
| freezegun | 0.3.12 | **1.5.2** — "Explicitly marks support for Python 3.13" | [CHANGELOG](https://github.com/spulec/freezegun/blob/master/CHANGELOG) |
| sseclient-py | 1.7 | Not mentioned in any release notes | [releases](https://github.com/mpetazzoni/sseclient/releases) |

=> as there are multiple big gaps, let's keep it as is and advised based on the auto test results
=> updated freezegun though as it was necessary ("AttributeError: module 'uuid' has no attribute `_load_system_functions`" error)


### requirements.txt
- pillow : 
	- pillow locals() + exec() incompatibility in Python 3.13 as PEP 667 changed how exec writes to locals()
	- pillow 11.1.0 has official support see https://github.com/python-pillow/Pillow/releases/tag/11.0.0
- weasyprint : weasyprint 63.0 requires Pillow < 11
	- In version 63.1 the upper bound was removed see [https://github.com/Kozea/WeasyPrint/releases/tag/v63.1](https://github.com/Kozea/WeasyPrint/releases/tag/v63.1)
- hapic : compatibility to Python 3.13 was made in the develop branch. Warning BC with marshmallow update !
- Two build failures, as they uses the private C API `_PyErr_WriteUnraisableMsg` which was removed in Python 3.13
	  - cffi https://github.com/python-cffi/cffi/releases/tag/v1.17.0 "Add support for Python 3.13"
	  - lxml https://pypi.org/project/lxml/5.3.0/#files cp313 wheels present (CPython 3.13)
  - `multidict==5.2.0` uses Py_TRASHCAN_SAFE_BEGIN/Py_TRASHCAN_SAFE_END which were removed in Python 3.13 
	  - https://github.com/aio-libs/multidict/releases/tag/v6.1.0 "Added support for Python 3.13"
  - pastedeploy
	  - ConfigParser.readfp was removed in Python 3.12. paste.deploy at line 64 uses it as the getattr default — which Python evaluates eagerly, crashing even though read_file exists
	  - pastedeploy https://docs.pylonsproject.org/projects/pastedeploy/en/latest/news.html v3.1.0 "Fix a broken compatibility shim that would cause the ConfigParser to fail on Python 3.12 when ConfigParser.readfp is removed" + "Support Python 3.11 and 3.12"
  - stevedore
	  - 'EntryPoints' object has no attribute 'items'
	  - https://docs.openstack.org/stevedore/latest/user/history.html#id6 v5.4.0 "Declare Python 3.12 support"
  - webob
	  - import cgi : module was removed in Python 3.13 (PEP 594)
	  - https://github.com/Pylons/webob/blob/1.8-branch/CHANGES.txt 1.8.9 added Python 3.13 support via the legacy-cgi package
  - zope-interface
	  - zope.interface.exceptions.InvalidInterface: Concrete attribute, __firstlineno__. Python 3.13 added __firstlineno__ as an automatic class attribute, and old zope.interface treats it as an invalid concrete attribute on interface classes
	  - zope-interface https://pypi.org/project/zope.interface/6.4.post2/ "Adjust for incompatible changes in Python 3.13b1"
  - pubcontrol : we were requesting for 3.2.0, but in version 3.5.0 a fix was made to be compatible with Python >= 3.10
	  - https://docs.python.org/3/whatsnew/changelog.html#changelog, Python 3.9.0 alpha 4: "bpo-39674: Revert “Do not expose abstract collection classes in the collections module” change (bpo-25988). Aliases to ABC like collections.Mapping are kept in Python 3.9 to ease transition from Python 2.7, but will be removed in Python 3.10."
	- pubcontrol commit [fanout/pypubcontrol@85307323](https://github.com/fanout/pypubcontrol/commit/85307323)
- pyparsing
	- matplotlib 3.11.0 requires pyparsing>=3, but you have pyparsing 2.4.7 which is incompatible.
	- transitive dep from preview-generator → vtk → matplotlib
	- `cliff==3.8.0` requires only pyparsing>=2.1.0, no upper bound
	- [https://github.com/pyparsing/pyparsing/releases/tag/3.1.2](https://github.com/pyparsing/pyparsing/releases/tag/3.1.2) "Support for Python 3.13."
- elasticsearch
	- numpy => np.float_ was removed in the NumPy 2.0 release. Use np.float64 instead
	- https://numpy.org/doc/stable/release/2.0.0-notes.html#numpy-2-0-python-api-removals
	- [https://github.com/elastic/elasticsearch-py/releases/tag/v7.17.12](https://github.com/elastic/elasticsearch-py/releases/tag/v7.17.12)  "Fix compatibility with NumPy 2.0"
- markdown
	- AttributeError: 'EntryPoints' object has no attribute 'get'
	- https://python-markdown.github.io/changelog/#342-2023-03-22 No mention to Python 3.13 in the changelog but only of 3.11 (3.4.2) and 3.14 (3.10.0)
	- Tracim uses only markdown.markdown() — the top-level conversion function — with no extensions, no internal API, no deprecated objects. None of the breaking changes between 3.3.4 and 3.10.0 affect Tracim.

### Debian bundled packages
#### PIP_BREAK_SYSTEM_PACKAGES
Env var added in tools_docker/Debian_Uwsgi/Dockerfile
Needed since Debian 12 to be able to process pip install without a venv. 
See [“Externally managed environments”: when PEP 668 breaks pip](https://pythonspeed.com/articles/externally-managed-environment-pep-668/)
#### pip install --ignore-installed
We were using `--force-reinstall`, but that is no longer possible because the Python packages bundled with the system do not include RECORD files and cannot be uninstalled via `pip`.
This is documented directly in the Dockerfile.

### Hapic, Marshmallow
Hapic needs to be updated to develop head (Damien worked on Python 3.13 compatibility with https://github.com/algoo/hapic/pull/219). 

But this version adds a new requirement: marshmallow 3.26.2. The dependency was already imported in Tracim with version 2.21.0, and used in Tracim backend code. The new version brings some depreciations / removals...

List of marshmallow modifications:

| Source                                                                                                                                                              | Version   | Description                                                                                            | Tracim status |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------- | ------------------------------------------------------------------------------------------------------ | ------------- |
| [Upgrading guide](https://marshmallow.readthedocs.io/en/3.x-line/upgrading.html#schemas-are-always-strict)                                                          | 2.x → 3.0 | `.dump().data` / `.load().errors` removed; methods now return data directly or raise `ValidationError` | **Fixed**     |
| [Email and URL fields should not validate on serialization · Issue #608 · marshmallow-code/marshmallow](https://github.com/marshmallow-code/marshmallow/issues/608) | 2.x → 3.0 | `ValidatedField` / `_validated` method removed                                                         | **Fixed**     |
| [3.x changelog](https://marshmallow.readthedocs.io/en/3.x-line/changelog.html#id59)                                                                                 | 3.0.0     | `Field.fail()` deprecated → `Field.make_error()`                                                       | _Not used_    |
| [2.x changelog](https://marshmallow.readthedocs.io/en/2.x-line/changelog.html#id14)                                                                                 | 2.19.0    | `fields.FormattedString` deprecated → `fields.Method` or `fields.Function`                             | _Not used_    |
| [3.x changelog](https://marshmallow.readthedocs.io/en/3.x-line/changelog.html#id47)                                                                                 | 3.3.0     | `fields.Nested('self', ...)` deprecated → use a callable instead                                       | _Not used_    |
| [3.x changelog](https://marshmallow.readthedocs.io/en/3.x-line/changelog.html#id40)                                                                                 | 3.7.0     | `marshmallow.pprint` deprecated                                                                        | _Not used_    |
| [3.x changelog](https://marshmallow.readthedocs.io/en/3.x-line/changelog.html#id35)                                                                                 | 3.10.0    | Passing metadata via kwargs (`example=`, `description=`) deprecated → `metadata={...}`                 | **Fixed**     |
| [3.x changelog](https://marshmallow.readthedocs.io/en/3.x-line/changelog.html#id29)                                                                                 | 3.13.0    | `missing=` / `default=` deprecated → `load_default=` / `dump_default=`                                 | **Fixed**     |
| [3.x changelog](https://marshmallow.readthedocs.io/en/3.x-line/changelog.html#id17)                                                                                 | 3.21.0    | `marshmallow.__version__` / `__parsed_version__` / `__version_info__` removed                          | _Not used_    |
| [3.x changelog](https://marshmallow.readthedocs.io/en/3.x-line/changelog.html#id8)                                                                                  | 3.24.0    | Validators returning `False` instead of raising `ValidationError`                                      | Not affected  |
| [3.x changelog](https://marshmallow.readthedocs.io/en/3.x-line/changelog.html#id8)                                                                                  | 3.24.0    | `context` parameter of Schema deprecated → `contextvars.ContextVar`                                    | _Not used_    |
| [3.x changelog](https://marshmallow.readthedocs.io/en/3.x-line/changelog.html#id8)                                                                                  | 3.24.0    | `Field`, `Mapping`, `Number` used directly as fields deprecated                                        | _Not used_    |
| [3.x changelog](https://marshmallow.readthedocs.io/en/3.x-line/changelog.html#id3)                                                                                  | 3.26.0    | `ordered` class Meta option deprecated                                                                 | _Not used_    |


#### Manually detected Marshmallow issues
Also I made some changes caused by v3 modifications: 
- by default extra fields are now rejected (Meta.unknown = RAISE), we need to use marshmallow.EXCLUDE as a workaround (see backend/tracim_backend/views/core_api/schemas.py : was blocking login !) => https://marshmallow.readthedocs.io/en/3.x-line/upgrading.html#schemas-raise-validationerror-when-deserializing-data-with-unknown-keys
- "decorators now pass `**kwargs` (e.g. many) to the decorated method signature" => added in methods signatures using `@post_load` => https://marshmallow.readthedocs.io/en/3.x-line/upgrading.html#decorated-methods-and-handle-error-receive-many-and-partial
- "load_from / dump_to → data_key → the two separate args were merged into a single data_key argument on Field" => https://marshmallow.readthedocs.io/en/3.x-line/upgrading.html#load-from-and-dump-to-are-merged-into-data-key

About ValidatedField removal: 2 Tracim classes concerned: RFCEmail and TracimEmail      
The `_validated` methods weren't needed anymore:
- they were ensuring None value wouldn't trigger a validator error
- in marshmallow 3.0 the None value won't be checked based on the allow_none option (see ‎Field.deserialize)
- in all existing calls to these 2 classes without allow_none we have required=True

Warning the dependency is also declared in backend/setup.py !

#### Auto tests broke by Marshmallow update

- backend/tracim_backend/tests/functional/test_workspaces.py : there were typo in field used, generating Marshmallow errors. Fixing fields name according to schema fixed the test.
- backend/tracim_backend/applications/agenda/controllers/radicale_proxy_controller.py : routes were having a `trailing_slash` capture that was rejected by the model. Removing the capture and adding 2 routes (one with trailing slash and one without) was an easy workaround
- schema.py
   - backend/tracim_backend/applications/collaborative_document_edition/wopi/schema.py : marshmallow.EXCLUDE (we are passing http headers) + load_from / dump_to → data_key
   - backend/tracim_backend/applications/upload_permissions/schema.py : marshmallow.EXCLUDE as "file_*" is invalid even in marshmallow 2, but our file_* fields were passing as default was EXCLUDE
   - backend/tracim_backend/views/core_api/schemas.py : load_from / dump_to → data_key
   - backend/tracim_backend/views/search_api/schemas.py : load_from / dump_to → data_key
- backend/tracim_backend/applications/collaborative_document_edition/wopi/lib.py : content.updated is a timezone-naive datetime but is semantically UTC. Marshmallow 2 would serialize it without +00:00 and the tests presumably didn't check for it. Marshmallow 3's DateTime field serializes naive datetimes without any timezone suffix, so the test started failing because the WOPI protocol expects ISO 8601 with timezone. The .replace(tzinfo=datetime.timezone.utc) is the minimal fix: it makes the datetime timezone-aware right before passing it to the model, so marshmallow 3 outputs +00:00. 



### pkgutil
`pkgutil._get_spec` was removed in Python 3.12 as part of the broader import system cleanup tracked in https://github.com/python/cpython/issues/98040
Replacement is importer.find_spec() see https://github.com/python/cpython/pull/98059/changes

## Other dependencies
### system
#### libmagickcore
Old libmagickcore-6.q16-6-extra isn't existing anymore, should be replaced by libmagickcore-7.q16-10-extra. We implemented a glob pattern and use `apt-get install` instead of `apt install`, and use the `libmagickcore-*-extra` pattern that will match (`apt-cache pkgnames 'libmagickcore-*-extra'` command) :
- libmagickcore-7.q16-10-extra ← what we need
- libmagickcore-7.q16hdri-10-extra ← Damien is ok to include it either

### libmagic1
libmagic1 is now libmagic1t64.
- package was there for:
    - bullseye (11): [https://packages.debian.org/search?suite=bullseye&searchon=names&keywords=libmagic1](https://packages.debian.org/search?suite=bullseye&searchon=names&keywords=libmagic1)
    - bookworm (12): [https://packages.debian.org/search?suite=bookworm&searchon=names&keywords=libmagic1](https://packages.debian.org/search?suite=bookworm&searchon=names&keywords=libmagic1)
- but replaced for trixie by libmagic1t64: [https://packages.debian.org/search?suite=trixie&searchon=names&keywords=libmagic1](https://packages.debian.org/search?suite=trixie&searchon=names&keywords=libmagic1)

#### libapache2-mod-proxy-uwsgi
libapache2-mod-proxy-uwsgi package removal :

1. Apache 2.4.33 (2018): mod_proxy_uwsgi was added directly into Apache as a built-in submodule. The separate libapache2-mod-proxy-uwsgi package was turned into a transitional dummy pointing to apache2.
2. Bookworm (Debian 12): The transitional package was still shipped to give users time to update their package lists — but it had no content, just a dependency on apache2.
3. Apache 2.4.59-1 (April 2024 → Trixie): The transitional package was explicitly dropped per [[Debian bug #1032628](https://www.mail-archive.com/debian-apache@lists.debian.org/msg18425.html)]([https://www.mail-archive.com/debian-apache@lists.debian.org/msg18425.html](https://www.mail-archive.com/debian-apache@lists.debian.org/msg18425.html)): "drop the transitional package after the release of bookworm, it has been released with buster and bullseye already." The package simply no longer exists in Trixie.

We are currently running Debian 11, which is bundled with Apache 2.4.67 ([https://packages.debian.org/bullseye/apache2](https://packages.debian.org/bullseye/apache2))

Package is present in system_packages/debian/server_packages.list. This file was created in commit [8f278bc](https://github.com/tracim/tracim/commit/8f278bcb6caf22af5d9e5b969c836b9beb3058ef), where we also modified tools_docker/Debian_Uwsgi/Dockerfile :

- switch hardcoded apt install to using server_packages.list file
- rename base_install to base
- base_install was debian:stretch, and base is debian:bullseye

Debian 9 Stretch was bundled with 2.4.25, so that would explain the presence of this package.

#### software-properties-common
Removed cause non existing in Trixie (see https://packages.debian.org/search?suite=all&searchon=names&keywords=software-properties-common).  
No issue detected.

It seems it was used for pushpin, but it is now installed using curl + gpg.

### Node16
There are no Debian 13 Trixie image with Node 16 (only versions 22, 24, 26)
We are switching to a Debian 13 image with manual install as the Dockerfile documents the way to install Tracim on Debian 13.


### Pushpin, Mongrel, Zurl

#### Concerned files
backend/pushpin_config/pushpin.conf
tools_docker/pushpin/Dockerfile
tools_docker/Debian_Uwsgi/Dockerfile

#### Install Pushpin
There is no package in Debian 13 repo:
- [https://tracker.debian.org/pkg/pushpin](https://tracker.debian.org/pkg/pushpin)
- [https://pushpin.org/docs/install/#debian-and-ubuntu](https://pushpin.org/docs/install/#debian-and-ubuntu)

Ways to install are:
1. using the pushpin apt repo (meant for Ubuntu and not Debian)
2. downloading the .deb file
3. Debian SID
4. Checking out code and compiling locally, as done in the official image Dockerfile https://github.com/fastly/pushpin/blob/main/docker/Dockerfile

We chose option 1.

Note that at that time 2 packages are available: 
- one for Ubuntu Noble (24.04)
    - => 🛑 fails to install due to a dependency error on libqt6network6t64. 
- and another one for Jammy (22.04)
   - => ✅ install is ok and it is running well too

As Pushpin can no longer be installed simply using apt now, a note was added in `system_packages/README.md`.    
The package itself is still present in `system_packages/debian/server_packages.list`.

#### Pushpin VS Condure & Zurl
Both libs were implemented directly into pushpin, see in [the changelog](https://github.com/fastly/pushpin/blob/main/CHANGELOG.md):

| Version | Date | Entry |
|---|---|---|
| v1.30.0 | 2020-07-29 | Optional support for Condure instead of Mongrel2. |
| v1.31.0 | 2020-11-06 | Use Condure instead of Mongrel2, by default. |
| v1.37.0 | 2023-06-29 | Ability to use Condure instead of Zurl for outgoing connections. |
| v1.38.0 | 2024-01-08 | Move Condure into Pushpin and name the program pushpin-condure. |
| v1.40.0 | 2024-07-17 | Rename Condure to connmgr. |

The default config is using `services=connmgr,proxy,handler` => we're now using those defaults !


#### SETUPTOOLS_USE_DISTUTILS
tools_docker/Debian_Uwsgi/Dockerfile
See #6711 (isn't relevant anymore for Python >= 3.12 and Setuptools >= 60.0.0)

### Cypress deps install
setup_functionnal_tests.sh
Changed by Damien

## Startup
### New errors
#### cache/config dirs
tools_docker/Debian_Uwsgi/Dockerfile
Error : "Fontconfig error: No writable cache directories"
Solution is documented inside the file

#### mime type application/javascript => text/javascript
Tests failing because with AssertionError: assert 'text/javascript' == 'application/javascript'

Change in default mime type in Debian 13, documented in #6864

#### "Document is empty" / "ink_file_open: cannot be opened"
backend/tracim_backend/tests/library/test_image_process.py

New warning on startup when doing db init, appeared after imagemagick update (from 6 to 7)
stderr output when generating avatars on DB init (svg to jpg conversion), no impact as avatars are generated. 
Didn't find a solution to get rid of those errors :( 

A closed issue about that : https://github.com/ImageMagick/ImageMagick/issues/7462

#### PangoFT2FontMap
Failed to wrap object of type 'PangoFT2FontMap' => no observed impact, referenced in open issue https://gitlab.com/inkscape/inkscape/-/work_items/5419

### Existing and not solved errors
- Deprecated config params (DEPOT_STORAGE_DIR, DEPOT_STORAGE_NAME, SMTP__USE_IMPLICIT_SSL) => created #6874
- HTTP/HTTPS warnings => expected when running locally
- Notification by email mechanism is disabled => expected
- AH00558: Could not reliably determine the server's fully qualified domain name => cosmetic, needs ServerName in apache config
- Restarting app server(s): uwsgi -> ! ! ! failed! => was already happening, doesn't seem to be an issue. entrypoint calls service uwsgi restart before uwsgi was ever started ?
- subprocess 1263 exited with code 128 => was already happening, not investigated yet ?

## Other
Fixed bug causing Fix "fatal : aucune étiquette ne correspond parfaitement à '...'" errors in test logs
Caused by last_commit that was including a line feed (`get_build_version()` in `backend/tracim_backend/lib/utils/utils.py`)

**Comment by piRGoif** [comment]
Added some info about Pushpin VS Condure / Zurl in https://github.com/tracim/tracim/issues/6859#issuecomment-5024991638
